spring.application.name=job-tracker

# Run the API on port 8080 during local dev
server.port=8080

# Disable persistent servlet sessions
server.servlet.session.persistent=false

# PostgreSQL database connection
# Environment variables are used when available
# Fallback values are for local development only
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/job_tracker}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:password}

# Let Hibernate create/update tables during development.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable Open Session in View because this project uses a service layer for database access
spring.jpa.open-in-view=false

app.security.username=${APP_USERNAME:admin}
app.security.password=${APP_PASSWORD:changeme}

# Expose only the health endpoint from Spring Boot Actuator
management.endpoints.web.exposure.include=health